(function(g){var window=this;'use strict';var io=function(O){O.isActive()||O.start()},Q0=function(O,b){return b?O.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},iSA=function(O){return g.R9(O)||O.Z("web_enable_caption_language_preference_stickiness")},eQ=function(O){var b={languageCode:O.languageCode,
languageName:O.languageName,displayName:g.ns(O),kind:O.kind,name:O.name,id:O.id,is_servable:O.T,is_default:O.isDefault,is_translateable:O.isTranslateable,vss_id:O.vssId};O.xtags&&(b.xtags=O.xtags);O.captionId&&(b.captionId=O.captionId);O.translationLanguage&&(b.translationLanguage=O.translationLanguage);return b},Qde=function(O,b){var a=new g.Jd;
a.languageCode=O.languageCode;a.languageName=O.languageName;a.name=O.name;a.displayName=O.displayName;a.kind=O.kind;a.isDefault=!1;a.T=O.T;a.isTranslateable=O.isTranslateable;a.vssId=O.vssId;a.url=O.url;a.translationLanguage=b;O.xtags&&(a.xtags=O.xtags);O.captionId&&(a.captionId=O.captionId);return a},eEB=function(O,b){var a,N,k;
return g.SG(function(D){if(D.T==1)return a=O+"|"+b,g.Y(D,g.QO(),2);if(D.T!=3){N=D.G;if(!N)throw g.Cz("gct");return g.Y(D,g.CL(N),3)}k=D.G;return D.return(k.get("captions",a))})},OVe=function(O,b,a){eEB(O,b).then(function(N){N&&a(N.trackData,new g.Jd(N.metadata))})},OI=function(O){if(!bVB.test(O))throw Error("'"+O+"' is not a valid hex color");
O.length==4&&(O=O.replace(akf,"#$1$1$2$2$3$3"));O=O.toLowerCase();O=parseInt(O.slice(1),16);return[O>>16,O>>8&255,O&255]},N43=function(){var O=void 0;
O=O===void 0?{}:O;var b="suggest_correction"in g.vj?g.vj.suggest_correction:"Edit caption";b=b||"";var a={},N;for(N in O){a={OY:a.OY};a.OY=N;var k=function(D){return function(){return String(O[D.OY])}}(a);
b=b.replace(new RegExp("\\$\\{"+a.OY+"\\}","gi"),k);b=b.replace(new RegExp("\\$"+a.OY,"gi"),k)}return b},bO=function(){return g.by("yt-player-caption-display-settings")},kTz=function(){this.G=[];
this.T=[]},ah=function(O,b){return b?O.T.concat(O.G):O.T},Nr=function(O,b){switch(b.kind){case "asr":DNp(b,O.G);
break;default:DNp(b,O.T)}},DNp=function(O,b){g.kU(b,function(a){return a?O.toString()===a.toString():!1})||b.push(O)},kP=function(O){g.m.call(this);
this.uV=O;this.G=new kTz;this.X=null;this.W=[];this.C=[]},DA=function(O,b,a){kP.call(this,O);
this.videoData=b;this.audioTrack=a;this.T=null;this.V=!1;this.W=b.sR;this.C=b.Ny;this.V=g.cl(b)},sC3=function(O,b,a){g.SG(function(N){O.T=g.K6(b,a);
g.qB(N)})},sI=function(){this.segments=[]},Roe=function(O,b){var a=g.ys(O.segments,b);
a>=0||a<0&&(-a-1)%2===1||(a=-a-1,a>0&&b-O.segments[a-1]===1&&a<O.segments.length&&O.segments[a]-b===1?(g.$U(O.segments,a),g.$U(O.segments,a-1)):a>0&&b-O.segments[a-1]===1?O.segments[a-1]=b:a<O.segments.length&&O.segments[a]-b===1?O.segments[a]=b:(g.Kx(O.segments,a,0,b),g.Kx(O.segments,a+1,0,b)))},Rh=function(O,b,a,N,k,D){g.m.call(this);
this.policy=O;this.player=b;this.yl=a;this.C=N;this.W=k;this.S=D;this.X=new sI;this.Y=-1;this.V=this.G=this.T=null;this.f8=0;this.U=new g.Hg(this.Un,1E3,this);this.events=new g.Re(this);g.n(this,this.U);g.n(this,this.events);this.events.j(b,"SEEK_COMPLETE",this.M7);this.M7();this.Un()},$NQ=function(O){return O.T&&O.T.Y?O.T.Y+O.player.yp()<O.player.getCurrentTime():!1},CH3=function(O,b){if(O.policy.QZ&&O.player.NU()){var a=g.OS(b,O.policy,{});
a.set("pot",O.player.NU());a=a.qJ()}else a=g.OS(b,O.policy,{}).qJ();var N={format:"RAW",withCredentials:!0};if(O.policy.aX){N.method="POST";var k=b.X;k&&Object.keys(k).length>0?N.postBody=g.uv(k,g.IE):N.postBody=(0,g.I_)([120,0])}O.W&&(N.responseType="arraybuffer");var D=++O.f8,R=(0,g.S)();O.V=g.uw(a,N,3,100,-1,function(d){d.errorCode==="net.timeout"&&O.player.lV("capnt",{rn:D++})}).then(function(d){if(O.policy.z9&&D%100===1){var Z=(0,g.S)();
O.player.lV("caprsp",{rn:D,ms:Z-R,kb:(d.xhr.responseText.length/1024).toFixed()})}a:{d=d.xhr;O.Xy();if(O.G){var F=!(O.W?d.response:d.responseText)||d.status>=400;if(Z=g.jv(d)){d=g.OS(O.G,O.policy,{});O.G.kt(d,Z);CH3(O,O.G);break a}if(F)O.player.lV("capfail",{status:d.status});else{var B;g.Kt("fcb_r",(0,g.S)(),((B=O.player.getVideoData())==null?void 0:B.yl)||"");B=O.G.EU[0].Gr;O.C!=null&&O.Y!==B&&(Z=O.G.EU[0],O.W?O.C(d.response,(Z.startTime+O.player.yp())*1E3):O.C(d.responseText,(Z.startTime+O.player.yp())*
1E3),O.Y=B)}}O.G=null;O.V=null}}).jW(function(d){O.G=null;
O.V=null;var Z;O.player.lV("capfail",{rn:D,status:(Z=d.xhr)==null?void 0:Z.status})});
O.G=b;Roe(O.X,O.G.EU[0].Gr)},$P=function(O,b){kP.call(this,b);
this.T=O;this.D=b;this.V=null;this.Y=!1;this.logger=new g.BX("caps");this.U=g.ku(this.D,this.T)},ZVA=function(O,b){var a=[],N;
for(N in O.T.T)if(O.T.T.hasOwnProperty(N)){var k=O.T.T[N];if(g.DV(k,b||null)){var D=k.info.id,R=D,d="."+D,Z="",F="";if(k=k.info.captionTrack)D=k.languageCode,R=k.displayName,d=k.vssId,Z=k.kind,F=k.id;else{k=D;var B=g.vce.get(k);B==null&&(B=dN3[k]||dN3[k.replace(/-/g,"_")],g.vce.set(k,B));k=B;R=k||R}a.push(new g.Jd({id:N,languageCode:D,languageName:R,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:d,kind:Z,captionId:F}))}}return a},FRB=function(O,b){return b!=null&&b in O.T.T?O.T.T[b]:null},
gwG=function(O,b,a){var N=[],k;
for(k in O.T.T)if(O.T.T.hasOwnProperty(k)){var D=O.T.T[k];if(g.DV(D,a||null)){var R=D.info.captionTrack;R&&R.languageCode===b&&N.push(D)}}return N.length?N[0]:null},C$=function(O,b,a,N,k,D){kP.call(this,O);
this.videoId=a;this.K_=k;this.eventId=D;this.Y={};this.T=null;O=N||g.XQ(b).hl||"";O=O.split("_").join("-");this.V=g.Qb(b,{hl:O})},dV=function(O){if(typeof DOMParser!="undefined")return g.zP(new DOMParser,g.cq(O),"application/xml");
throw Error("Your browser does not support loading xml documents");},ZA=function(O,b,a,N,k,D,R,d,Z,F){var B=F.isInline()&&!0,K={};
Object.assign(K,b);Object.assign(K,O.params);Object.assign(K,a);var t={};Object.assign(t,b.Y1);O.params.Y1&&Object.assign(t,O.params.Y1);Object.assign(t,a.Y1);B&&(K.windowOpacity=.6,t.backgroundOpacity=0);K.Y1=t;var h=K.Db===1,w=[{N:"span",Mi:"captions-text",K:{style:"word-wrap: normal; display: block;"}}],A,W,E;(d=d.eL("caption_edit_on_hover")&&((A=F.getVideoData().getPlayerResponse())==null?void 0:(W=A.captions)==null?void 0:(E=W.playerCaptionsTracklistRenderer)==null?void 0:E.openTranscriptCommand))&&
w.unshift({N:"button",Mi:"caption-edit",K:{tabindex:"0","aria-label":N43()},vy:[{N:"svg",K:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},vy:[{N:"path",K:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.L.call(this,{N:"div",Mi:"caption-window",K:{id:"caption-window-"+O.id,dir:h?"rtl":"ltr",tabindex:"0",lang:K.lang},vy:w});
var z=this;this.U=[];this.n8=!1;this.G=O;this.ZG=this.aX=null;this.WB=D;this.Vp=R;this.C=null;this.maxWidth=D*.96;this.maxHeight=R*.96;this.T=K;this.Go=a;this.f8=b;this.X=this.DG("captions-text");this.SL=this.X.style.getPropertyValue("box-decoration-break")!==""||this.X.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Yk=B4G(N,k,D,R);this.vB=Z;d&&(this.Y=this.DG("caption-edit"),this.j(this.Y,"click",function(){z.vB()}));
this.type=0;this.UU=this.Yk*KRY(t);this.K8=B;O=new g.G0(this.element,!0);g.n(this,O);O.subscribe("dragstart",this.YP,this);O.subscribe("dragmove",this.ut,this);O.subscribe("dragend",this.gp,this);this.iV=this.hN=this.Fy=this.By=0;O="";this.T.windowOpacity&&(O=OI(this.T.windowColor),O="rgba("+O[0]+","+O[1]+","+O[2]+","+this.T.windowOpacity+")");b={"background-color":O,display:this.T.isVisible===!1?"none":"","text-align":txQ[this.T.textAlign]};this.SL&&(b["border-radius"]=O?this.UU/8+"px":"");(this.V=
this.G.params.Db===2||this.G.params.Db===3)&&hoz(this,this.element);g.EE(this.element,b);if(B){var J;(J=this.element.parentElement)==null||J.style.setProperty("--caption-window-color",O)}switch(this.T.DW){case 0:case 1:case 2:g.oo(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.oo(this.element,"ytp-caption-window-bottom")}},hoz=function(O,b){var a="vertical-rl";
O.T.DF===1&&(a="vertical-lr");g.MI&&(a=a==="vertical-lr"?"tb-lr":"tb-rl");g.EE(b,"-o-writing-mode",a);g.EE(b,"-webkit-writing-mode",a);g.EE(b,"writing-mode",a);g.EE(b,"text-orientation","upright");g.oo(b,"ytp-vertical-caption");O.G.params.Db===3&&(g.EE(b,"text-orientation",""),g.EE(b,"transform","rotate(180deg)"))},KRY=function(O){var b=1+.25*(O.fontSizeIncrement||0);
if(O.offset===0||O.offset===2)b*=.8;return b},ypz=function(O,b){var a={},N=b.background?b.background:O.T.Y1.background;
if(b.backgroundOpacity!=null||b.background){var k=b.backgroundOpacity!=null?b.backgroundOpacity:O.T.Y1.backgroundOpacity;N=OI(N);a.background="rgba("+N[0]+","+N[1]+","+N[2]+","+k+")";O.SL&&(a["box-decoration-break"]="clone",a["border-radius"]=O.UU/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)a["font-size"]=O.Yk*KRY(b)+"px";N=1;k=b.color||O.T.Y1.color;if(b.color||b.textOpacity!=null)k=OI(k),N=b.textOpacity==null?O.T.Y1.textOpacity:b.textOpacity,k="rgba("+k[0]+","+k[1]+","+k[2]+","+N+")",a.color=
k,a.fill=k;var D=b.charEdgeStyle;D===0&&(D=void 0);if(D){k="rgba(34, 34, 34, "+N+")";var R="rgba(204, 204, 204, "+N+")";b.H_&&(R=k=b.H_);var d=O.Yk/16/2,Z=Math.max(d,1),F=Math.max(2*d,1),B=Math.max(3*d,1),K=Math.max(5*d,1);N=[];switch(D){case 4:for(;B<=K;B+=d)N.push(F+"px "+F+"px "+B+"px "+k);break;case 1:F=window.devicePixelRatio>=2?.5:1;for(D=Z;D<=B;D+=F)N.push(D+"px "+D+"px "+k);break;case 2:N.push(Z+"px "+Z+"px "+R);N.push("-"+Z+"px -"+Z+"px "+k);break;case 3:for(B=0;B<5;B++)N.push("0 0 "+F+"px "+
k)}a["text-shadow"]=N.join(", ")}k="";switch(b.fontFamily){case 1:k='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:k='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:k='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:k='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:k='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:k=g.vb()?'"Carrois Gothic SC", sans-serif-smallcaps':
'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:k='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}k&&(a["font-family"]=k);k=b.offset;k==null&&(k=O.T.Y1.offset);switch(k){case 0:a["vertical-align"]="sub";break;case 2:a["vertical-align"]="super"}b.fontFamily===7&&(a["font-variant"]="small-caps");b.bold&&(a["font-weight"]="bold");b.italic&&(a["font-style"]="italic");b.underline&&(a["text-decoration"]="underline");b.C6&&(a.visibility="hidden");
b.Ff===1&&O.V&&(a["text-combine-upright"]="all",a["text-orientation"]="mixed",k=g.S6||g.Rp,O.G.params.Db===3?a.transform=k?"rotate(90deg)":"rotate(180deg)":k&&(a.transform="rotate(-90deg)"));if(b.textEmphasis===1||b.textEmphasis===2||b.textEmphasis===3||b.textEmphasis===4||b.textEmphasis===5)if(g.S6)a["font-weight"]="bold";else switch(a["text-emphasis-style"]="filled circle",a["text-emphasis-color"]="currentcolor",a["webkit-text-emphasis"]="filled circle",b.textEmphasis){case 4:case 3:a["text-emphasis-position"]=
"under left";a["webkit-text-emphasis-position"]="under left";break;case 5:case 2:a["text-emphasis-position"]="over right",a["webkit-text-emphasis-position"]="over right"}return a},Fw=function(O){O=O.split("px");
return O.length>0?(O=Number(O[0]))?O:0:0},wSG=function(O){O.C=g.Ms("SPAN");
g.EE(O.C,{display:"block"});g.oo(O.C,"caption-visual-line");O.X.appendChild(O.C)},T4b=function(O,b){var a=g.Ms("SPAN");
g.EE(a,{display:"inline-block","white-space":"pre-wrap"});g.EE(a,ypz(O,b));a.classList.add("ytp-caption-segment");O.C.appendChild(a);a.previousElementSibling&&(g.EE(a.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.EE(a,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return a},rpw=function(O,b,a){O.n8=O.n8||!!a;
var N={};Object.assign(N,O.T.Y1);Object.assign(N,a||b.T);Object.assign(N,O.Go.Y1);(a=!O.C)&&wSG(O);for(var k=O.aX&&O.ZG&&g.T8(N,O.ZG)?O.aX:T4b(O,N),D=typeof b.text==="string",R=D?b.text.split("\n"):[b.text],d=0;d<R.length;d++){var Z=d>0||!b.append,F=R[d];Z&&!a?(wSG(O),k=T4b(O,N)):Z&&a&&(a=!1);F&&(k.appendChild(D?document.createTextNode(String(F)):F),D||F.tagName!=="RUBY"||F.childElementCount!==4||g.S6||!g.pb(F.children[2],"text-emphasis")||(Z=O.V?"padding-right":"padding-top",g.pb(F.children[2],"text-emphasis-position")&&
(Z=O.V?"padding-left":"padding-bottom"),g.z8?g.EE(k,Z,"1em"):g.EE(k,Z,"0.5em")))}O.ZG=N;O.aX=k;O.U.push(b)},B4G=function(O,b,a,N){var k=b/360*16;
b>=O&&(O=640,N>a*1.3&&(O=480),k=a/O*16);return k},BY=function(){this.V=this.time=this.mode=this.G=0;
this.X=new gV(this);this.W=new gV(this);this.T=[];this.clear()},uUB=function(O,b,a){if(O===255&&b===255||!O&&!b)return{rT:O,
D8:b,result:0};O=UN3[O];b=UN3[b];if(O&128){var N;if(N=!(b&128))N=b,N=a.NJ()&&a.D8===N;if(N)return{rT:O,D8:b,result:1}}else if(b&128&&1<=O&&O<=31)return{rT:O,D8:b,result:2};return{rT:O,D8:b,result:3}},WRe=function(O,b,a,N){b===255&&a===255||!b&&!a?(++O.V===45&&O.reset(),O.X.G.clear(),O.W.G.clear()):(O.V=0,ApQ(O.X,b,a,N))},qdY=function(O,b){O.T.sort(function(k,D){var R=k.time-D.time;
return R===0?k.order-D.order:R});
for(var a=g.H(O.T),N=a.next();!N.done;N=a.next())N=N.value,O.time=N.time,N.type===0?WRe(O,N.sN,N.Tm,b):N.type===1&&O.G&496&&ApQ(O.W,N.sN,N.Tm,b);O.T.length=0},K$=function(){this.type=0},t6=function(){this.state=this.D8=this.rT=0},HVe=function(){this.timestamp=this.T=0},h6=function(O){this.W=O;
this.V=[];this.T=this.G=this.row=0;this.style=new K$;for(O=this.X=0;O<=15;O++){this.V[O]=[];for(var b=0;b<=32;b++)this.V[O][b]=new HVe}},yA=function(O,b){if(O.style.type===3){for(var a=0,N=0,k=O.W.time+0,D="",R="",d=k,Z=1;Z<=15;++Z){for(var F=!1,B=N?N:1;B<=32;++B){var K=O.V[Z][B];
if(K.T!==0){a===0&&(a=Z,N=B);F=String.fromCharCode(K.T);var t=K.timestamp;t<k&&(k=t);K.timestamp=d;R&&(D+=R,R="");D+=F;F=!0}if((K.T===0||B===32)&&F){R="\n";break}else if(N&&!F)break}if(a&&!F)break}D&&b.X(a,N,k,d,D)}else for(N=a=0,D=k=O.W.time+0,R=1;R<=15;++R)for(d="",Z=1;Z<=32;++Z)if(B=O.V[R][Z],K=B.T,K!==0&&(a===0&&(a=R,N=Z),F=String.fromCharCode(K),t=B.timestamp,t<=k&&(k=t),d+=F,B.reset()),Z===32||K===0)d&&b.X(a,N,k,D,d),k=D,d="",N=a=0},JpG=function(O,b){switch(O){case 0:return Yd7[(b&127)-32];
case 1:return cpw[b&15];case 2:return mNf[b&31];case 3:return zoG[b&31]}return 0},wV=function(O){return O.V[O.row][O.G]},Tt=function(O,b,a){b>=2&&O.G>1&&(--O.G,wV(O).T=0);
var N=wV(O);N.timestamp=O.W.time+0;N.T=JpG(b,a);O.G<32&&O.G++},Ewz=function(O,b,a,N){for(var k=0;k<N;k++)for(var D=0;D<=32;D++){var R=O.V[b+k][D],d=O.V[a+k][D];
R.T=d.T;R.timestamp=d.timestamp}},rV=function(O,b,a){for(var N=0;N<a;N++)for(var k=0;k<=32;k++)O.V[b+N][k].reset()},UI=function(O){O.row=O.T>0?O.T:1;
O.G=1;rV(O,0,15)},uO=function(O){this.V=O;
this.W=0;this.style=new K$;this.Y=new h6(this.V);this.U=new h6(this.V);this.text=new h6(this.V);this.G=this.Y;this.X=this.U;this.T=this.G},A6=function(O,b,a){var N=O.G,k=!1;
switch(O.style.get()){case 4:case 1:case 2:O.style.get()===4&&N.T>0||(yA(N,a),UI(O.G),UI(O.X),N.row=15,N.T=b,k=!0)}O.style.set(3);O.T=N;O.T.style=O.style;O.V.mode=1<<N.X;k?N.G=1:N.T!==b&&(N.T>b?(yA(N,a),rV(N,N.row-N.T,b)):N.row<b&&(b=N.T),N.T=b)},Mxe=function(O){O.style.set(1);
O.T=O.X;O.T.T=0;O.T.style=O.style;O.V.mode=1<<O.T.X},nwf=function(O){O.style.set(4);
O.T=O.text;O.T.style=O.style;O.V.mode=1<<O.T.X},gV=function(O){this.T=O;
this.W=0;this.V=new uO(this.T);this.Y=new uO(this.T);this.G=new t6;this.X=this.V},ApQ=function(O,b,a,N){O.G.update();
b=uUB(b,a,O.G);switch(b.result){case 0:return;case 1:case 2:return}var k=b.rT;a=b.D8;if(32<=k||!k)O.T.mode&O.T.G&&(b=k,b&128&&(b=127),a&128&&(a=127),O=O.X.T,b&96&&Tt(O,0,b),a&96&&Tt(O,0,a),b!==0&&a!==0&&O.style.type===3&&yA(O,N));else if(k&16)a:if(!O.G.matches(k,a)&&(b=O.G,b.rT=k,b.D8=a,b.state=2,b=k&8?O.Y:O.V,O.X=b,O.T.mode=1<<(O.W<<2)+(b.W<<1)+(b.style.type===4?1:0),(O.T.mode|1<<(O.W<<2)+(b.W<<1)+(b.style.type!==4?1:0))&O.T.G))if(a&64){N=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(k&7)<<1|a>>5&1];
O=a&16?((a&14)>>1)*4:0;a=b.T;switch(b.style.get()){case 4:N=a.row;break;case 3:if(N!==a.row){if(N<a.T&&(N=a.T,N===a.row))break;var D=1+a.row-a.T,R=1+N-a.T;Ewz(a,R,D,a.T);b=D;k=a.T;R<D?(D=R+k-D,D>0&&(b+=D,k-=D)):(D=D+k-R,D>0&&(k-=D));rV(a,b,k)}}a.row=N;a.G=O+1}else switch(k&7){case 1:switch(a&112){case 32:Tt(b.T,0,32);break a;case 48:a===57?(N=b.T,wV(N).T=0,N.G<32&&N.G++):Tt(b.T,1,a&15)}break;case 2:a&32&&Tt(b.T,2,a&31);break;case 3:a&32&&Tt(b.T,3,a&31);break;case 4:case 5:if(32<=a&&a<=47)switch(a){case 32:Mxe(b);
break;case 33:N=b.T;N.G>1&&(--N.G,wV(N).T=0);break;case 36:N=b.T;b=wV(N);for(O=0;O<=15;O++)for(a=0;a<=32;a++)if(N.V[O][a]===b){for(;a<=32;a++)N.V[O][a].reset();break}break;case 37:A6(b,2,N);break;case 38:A6(b,3,N);break;case 39:A6(b,4,N);break;case 40:Tt(b.T,0,32);break;case 41:b.style.set(2);b.T=b.G;b.T.T=0;b.T.style=b.style;b.V.mode=1<<b.T.X;break;case 42:N=b.text;N.T=15;N.style.set(4);UI(N);nwf(b);break;case 43:nwf(b);break;case 44:O=b.G;switch(b.style.get()){case 1:case 2:case 3:yA(O,N)}rV(O,
0,15);break;case 45:b:{O=b.T;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(O.row<15){++O.row;O.G=1;break b}break;case 3:}O.T<2&&(O.T=2,O.row<O.T&&(O.row=O.T));b=O.row-O.T+1;yA(O,N);Ewz(O,b,b+1,O.T-1);rV(O,O.row,1)}break;case 46:rV(b.X,0,15);break;case 47:yA(b.G,N),b.X.updateTime(b.V.time+0),N=b.X,b.X=b.G,b.G=N,Mxe(b)}break;case 7:switch(a){case 33:case 34:case 35:N=b.T,(N.G+=a&3)>32&&(N.G=32)}}},pSe=function(){},WY=function(O,b,a,N,k,D,R){D=D===void 0?!1:D;
R=R===void 0?null:R;g.f8.call(this,O,O+b,{priority:a,namespace:"captions"});this.windowId=N;this.text=k;this.append=D;this.T=R},owQ=function(O,b,a,N,k,D,R){var d=D[0],Z=R[d.getAttribute("p")];
if(Z.Md===1){var F=D[1],B=D[2];D=D[3];d.getAttribute("t");F.getAttribute("t");B.getAttribute("t");D.getAttribute("t");d.getAttribute("p");F.getAttribute("p");D.getAttribute("p");R=R[B.getAttribute("p")];d=GTe(d.textContent,F.textContent,B.textContent,D.textContent,R);return new WY(O,b,k,a,d,N,Z)}switch(Z.Md){case 9:case 10:Z.textEmphasis=1;break;case 11:Z.textEmphasis=2;break;case 12:Z.textEmphasis=3;break;case 13:Z.textEmphasis=4;break;case 14:Z.textEmphasis=5}return new WY(O,b,k,a,d.textContent||
"",N,Z)},GTe=function(O,b,a,N,k){var D=g.vb(),R=D?g.Ms("DIV"):g.Ms("RUBY"),d=g.Ms("SPAN");
d.textContent=O;R.appendChild(d);O=D?g.Ms("DIV"):g.Ms("RP");O.textContent=b;R.appendChild(O);b=D?g.Ms("DIV"):g.Ms("RT");b.textContent=a;R.appendChild(b);a=k.Md;if(a===10||a===11||a===12||a===13||a===14)if(g.EE(b,"text-emphasis-style","filled circle"),g.EE(b,"text-emphasis-color","currentcolor"),g.EE(b,"webkit-text-emphasis","filled circle"),k.Md===11||k.Md===13)g.EE(b,"webkit-text-emphasis-position","under left"),g.EE(b,"text-emphasis-position","under left");a=!0;if(k.Md===4||k.Md===7||k.Md===12||
k.Md===14)g.EE(R,"ruby-position","over"),g.EE(R,"-webkit-ruby-position","before");else if(k.Md===5||k.Md===6||k.Md===11||k.Md===13)g.EE(R,"ruby-position","under"),g.EE(R,"-webkit-ruby-position","after"),a=!1;k=D?g.Ms("DIV"):g.Ms("RP");k.textContent=N;R.appendChild(k);D&&(N=a,g.EE(R,{display:"inline-block",position:"relative"}),D=R.firstElementChild.nextElementSibling,g.EE(D,"display","none"),D=D.nextElementSibling,g.EE(D,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.EE(R.lastElementChild,"display","none"),N?(g.EE(R,"padding-top","0.6em"),g.EE(D,"top","0")):(g.EE(R,"padding-bottom","0.6em"),g.EE(D,"bottom","0")));return R},qr=function(){g.m.apply(this,arguments)},HY=function(O,b,a,N,k){g.f8.call(this,O,O+b,{priority:a,
namespace:"captions"});this.id=N;this.params=k;this.T=[]},xNw=function(O){var b="_"+YP++;
return new HY(0,0x8000000000000,0,b,O)},cY=function(O){qr.call(this);
this.X=O;this.pens={};this.C={};this.S={};this.W="_"+YP++;this.U={};this.G=this.T=null;this.Y=!0},m$=function(O,b){O=O.getAttribute(b);
if(O!=null)return Number(O)},zt=function(O,b){O=O.getAttribute(b);
if(O!=null)return O==="1"},J6=function(O,b){O=m$(O,b);
return O!==void 0?O:null},Mr=function(O,b){O=O.getAttribute(b);
if(O!=null)return EI.test(O),O},PHQ=function(O,b){var a={},N=b.getAttribute("ws");
Object.assign(a,N?O.S[N]:O.X);O=J6(b,"mh");O!=null&&(a.kU=O);O=J6(b,"ju");O!=null&&(a.textAlign=O);O=J6(b,"pd");O!=null&&(a.Db=O);O=J6(b,"sd");O!=null&&(a.DF=O);O=Mr(b,"wfc");O!=null&&(a.windowColor=O);b=m$(b,"wfo");b!==void 0&&(a.windowOpacity=b/255);return a},vwz=function(O,b){var a={},N=b.getAttribute("wp");
N&&Object.assign(a,O.C[N]);O=J6(b,"ap");O!=null&&(a.DW=O);O=m$(b,"cc");O!=null&&(a.UR=O);O=m$(b,"ah");O!=null&&(a.EF=O);O=m$(b,"rc");O!=null&&(a.HG=O);b=m$(b,"av");b!=null&&(a.Am=b);return a},jC3=function(O,b,a,N){var k={};
Object.assign(k,vwz(O,b));Object.assign(k,PHQ(O,b));N?g.T8(k,O.X)?(N=O.W,k=O.X):N="_"+YP++:N=b.getAttribute("id")||"_"+YP++;O=m$(b,"t")+a;b=m$(b,"d")||0x8000000000000;if(k.Db===2||k.Db===3)a=k.HG,k.HG=k.UR,k.UR=a;return new HY(O,b,0,N,k)},n$=function(O){qr.call(this);
this.Y=O;this.T=new Map;this.X=new Map;this.W=new Map;this.G=new Map},p$=function(O){O=g.Vw(Math.round(O),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-O.length)+O},Sdf=function(O,b,a,N,k){N===0&&(N=0x8000000000000);
var D={};b.wpWinPosId&&Object.assign(D,O.X.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(D,O.W.get(b.wsWinStyleId));O=b.rcRowCount;O!==void 0&&(D.HG=O);b=b.ccColCount;b!==void 0&&(D.UR=b);if(D.Db===2||D.Db===3)b=D.HG,D.HG=D.UR,D.UR=b;return new HY(a,N,0,k,D)},Gt=function(O,b,a){kP.call(this,O);
this.videoData=b;this.audioTrack=a;this.W=b.sR},oh=function(O,b,a,N,k,D,R,d,Z,F){ZA.call(this,O,b,a,N,k,D,R,d,Z,F);
this.type=1},xP=function(O,b,a){this.trackData=O;
this.Y=a;this.version=this.W=this.V=this.byteOffset=0;this.G=[];this.T=new DataView(this.trackData)},PY=function(O){var b=O.byteOffset;
O.byteOffset+=1;return O.T.getUint8(b)},vY=function(O){var b=O.byteOffset;
O.byteOffset+=4;return O.T.getUint32(b)},jc=function(O,b){qr.call(this);
this.G=O;this.X=b;this.track=this.X.languageName==="CC3"?4:0;this.T=new BY;this.T.G=1<<this.track},fk7=function(O){if(typeof O==="string")return!1;
O=new xP(O,8,0);return Ikb(O)},Ikb=function(O){if(!(O.byteOffset<O.T.byteLength)||vY(O)!==1380139777)return!1;
O.version=PY(O);if(O.version>1)return!1;PY(O);PY(O);PY(O);return!0},Sc=function(O,b,a,N,k,D,R,d,Z,F){ZA.call(this,O,b,a,N,k,D,R,d,Z,F);
var B=this;this.type=2;this.wd=[];this.yl=this.S=this.Py=0;this.sU=NaN;this.p8=0;this.Ql=null;this.RX=new g.Hg(this.OA,433,this);this.Y&&(F.createClientVe(this.Y,this,167342),this.j(this.Y,"click",function(){F.logClick(B.Y)}),O=new g.G0(this.element,!0),g.n(this,O),O.subscribe("hoverstart",function(){F.logVisibility(B.Y,!0)},this));
g.oo(this.element,"ytp-caption-window-rollup");g.n(this,this.RX);g.EE(this.element,"overflow","hidden")},lkb=function(O,b){if(!b)return"";
O.V&&O.G.params.DF!==1&&(b*=-1);return"translate"+(O.V?"X":"Y")+"("+b+"px)"},Vxz=function(O){O.wd=Array.from(O.element.getElementsByClassName("caption-visual-line"));
for(var b=O.G.params.HG,a=0,N=0,k=O.wd.length-1;a<b&&k>-1;){var D=O.wd[k];N+=O.V?D.offsetWidth:D.offsetHeight;a++;k--}O.S=N;b=Math;a=b.max;isNaN(O.sU)&&((N=O.T.UR)?(k=g.Ms("SPAN"),g.Pv(k,"\u2013".repeat(N)),g.EE(k,ypz(O,O.T.Y1)),O.X.appendChild(k),O.sU=k.offsetWidth,O.X.removeChild(k)):O.sU=0);N=O.X;O.yl=a.call(b,O.sU,O.p8,(O.V?N.offsetHeight:N.offsetWidth)+1)},LRb=function(O,b){Vxz(O);
var a=O.wd.reduce(function(D,R){return(O.V?R.offsetWidth:R.offsetHeight)+D},0);
a=O.S-a;if(a!==O.Py){var N=a>0&&O.Py===0,k=a<O.Py;b||isNaN(a)||N||!k||(g.oo(O.element,"ytp-rollup-mode"),O.j(O.element,"transitionend",O.OA));g.EE(O.X,"transform",lkb(O,a));O.Py=a}Vxz(O)},Ih=function(O,b,a,N){var k=this;
this.D=O;this.X=b;this.logger=a;this.G=N;this.XX=[];this.R0=[];this.T=null;this.qt={s$:function(){return k.T},
I3:function(){return k.XX}};
O=g.f(this.D.J().experiments,"html5_override_micro_discontinuities_threshold_ms");this.V=O>0?O:10},QCB=function(O,b){O.T=function(a,N){if(a.info.W){var k=a;
if(O.R0.length>0){for(k=O.R0.shift();O.R0.length>0;)k=g.r$(k,O.R0.shift());k=g.r$(k,a)}if(k){a=k;try{var D=g.uW(a)*1E3}catch(F){D=a.info.startTime*1E3}try{var R=g.YF(a)*1E3}catch(F){R=a.info.duration*1E3}if(D<0||R<0)D<0&&(D=a.info.startTime*1E3),R<0&&(R=a.info.duration*1E3);a.info.startTime=D/1E3;a.info.X=D/1E3;a.info.duration=R/1E3;a.info.C=R/1E3;D=O.W$(k);R=D.Gr;D={formatId:D.formatId,startTimeMs:D.startTimeMs,durationMs:D.durationMs,Vi:R,Ji:R};R=XS3(O.XX,D.startTimeMs);var d=(a=R>=0?O.XX[R]:null)?
a.startTimeMs+a.durationMs:0,Z=D.startTimeMs+D.durationMs;!a||D.startTimeMs-d>O.V?O.XX.splice(R+1,0,D):(a.durationMs=Math.max(d,Z)-a.startTimeMs,a.Ji=Math.max(a.Ji,D.Ji));N(O.XX);N=g.w$(k);iVb(O.X,N.buffer.slice(N.byteOffset,N.byteLength+N.byteOffset),b,k.info.X)}else O.logger.T(350058965,"Empty slice")}else O.R0.push(a)};
O.D.addEventListener("sabrCaptionsDataLoaded",O.T)},XS3=function(O,b){O=g.ys(O,{startTimeMs:b},function(a,N){return a.startTimeMs-N.startTimeMs});
return O>=0?O:-O-2},f$=function(O,b){kP.call(this,b);
this.T=O;this.D=b;this.logger=new g.BX("caps");this.V=this.Y=null;this.U=new Ih(this.D,this,this.logger,this.T.G)},iVb=function(O,b,a,N){O.logger.debug(function(){return"SABR captions data received for "+N});
O.Y?O.V==null?O.logger.T(350058965,"Null loaded track meta data at captions data received"):a.aN(b,O.V,N*1E3):O.logger.T(350058965,"Null Representation at captions data received")},eop=function(O,b){var a=[],N;
for(N in O.T.T)if(O.T.T.hasOwnProperty(N)){var k=O.T.T[N];if(g.DV(k,b||null)){var D=k.info.id,R=D,d="."+D,Z="",F="";if(k=k.info.captionTrack)D=k.languageCode,R=k.displayName,d=k.vssId,Z=k.kind,F=k.id;a.push(new g.Jd({id:N,languageCode:D,languageName:R,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:d,kind:Z,captionId:F}))}}return a},OpB=function(O,b,a){var N=[],k;
for(k in O.T.T)if(O.T.T.hasOwnProperty(k)){var D=O.T.T[k];if(g.DV(D,a||null)){var R=D.info.captionTrack;R&&R.languageCode===b&&N.push(D)}}return N.length?N[0]:null},bpz=function(O,b){if(!g.GN(O)||O.T!=null&&g.ku(b,O.T)&&O.T.T.rawcc!=null)return!1;
b=!!O.T&&O.T.isManifestless&&Object.values(O.T.T).some(function(a){return g.DV(a,"386")});
O=!!O.T&&!O.T.isManifestless&&g.Xm(O.T);return b||O},lO=function(){qr.call(this)},NW3=function(O){var b=aXY.length;
if(O.byteLength<b)return!1;O=new Uint8Array(O,0,b);for(var a=0;a<b;a++)if(aXY[a]!==O[a])return!1;return!0},kCe=function(O,b,a,N,k,D,R,d,Z){switch(R.tagName){case "b":d.bold=!0;
break;case "i":d.italic=!0;break;case "u":d.underline=!0}for(var F=0;F<R.childNodes.length;F++){var B=R.childNodes[F];if(B.nodeType===3)B=new WY(b,a,N,k.id,B.nodeValue,D||F>0,g.hc(d)?void 0:d),Z.push(B),k.T.push(B);else{var K={};Object.assign(K,d);kCe(O,b,a,N,k,!0,B,K,Z)}}},VA=function(O){var b=O.split(":");
O=0;b=g.H(b);for(var a=b.next();!a.done;a=b.next())O=O*60+Number(a.value);return O*1E3},Dcp=function(O,b,a,N){N=Object.assign({kU:0},N);
return new HY(O,b,a,"_"+YP++,N)},L$=function(O,b){g.m.call(this);
this.D=O;this.B=b;this.T=null;this.G=this.D.u4();this.logger=new g.BX("caps")},RQG=function(O,b,a){if(typeof b==="string"||fk7(b))return[{trackData:b,
Pp:a}];if(typeof b==="string"&&b.substring(0,6)==="WEBVTT"||typeof b!=="string"&&NW3(b))return[{trackData:b,Pp:a}];var N=new DataView(b);if(N.byteLength<=8||N.getUint32(4)!==1718909296)return[];var k=g.Jp(N);if(O.G&&k){var D=g.yo(k),R=g.w4(k);k=k.fl;D&&k&&O.G.ov(k,D,R)}O=g.MN(N,1835295092);if(!O||!O.length||!O[0].size)return[];D=[];for(R=0;R<O.length;R++)k=O[R],k=new Uint8Array(b,k.dataOffset,k.size-(k.dataOffset-k.offset)),k=g.iT(k),D.push({trackData:k,Pp:a+R*1E3});srb(N,D,a);return D=D.filter(function(d){return!!d.trackData})},
srb=function(O,b,a){var N=g.r4(O,0,1836476516),k=9E4;
N&&(k=g.uH(N)||9E4);N=0;for(var D=g.MN(O,1836019558),R=0;R<D.length;R++){var d=D[R];R<b.length&&(d=g.r4(O,d.dataOffset,1953653094))&&(d=g.r4(O,d.dataOffset,1952867444))&&(d=g.cS(d)/k*1E3,R===0&&(N=d),b[R].Pp=d-N+a||a*R*1E3)}},$ce=function(O,b,a){O.T||(O.T=new lO);
O=O.T.V(b,a);Math.random()<.01&&g.Z2(Error("Deprecated subtitles format in web player: WebVTT"));return O},C5f=function(O){var b={};
if(O=g.Ey(O))b.lang=O,g.lcf.test(O)&&(b.Db=1);return b},iO=function(O){g.NW.call(this,O);
var b=this;this.D=O;this.aX=[];this.wd={};this.UU={};this.Y=!1;this.X="NONE";this.G=this.S=this.yl=this.Yk=this.By=null;this.RX={Kl:function(){b.Kl()},
aN:function(D,R,d,Z){b.aN(D,R,d,Z)}};
this.T=null;this.B=this.D.J();this.videoData=this.D.getVideoData();this.Fy=this.D.jL();this.V={Y1:{}};this.U={Y1:{}};g.f5(this.videoData)?this.X="OFFLINE":bpz(this.videoData,this.D)?this.X="SABR_LIVE":g.zee(this.videoData,this.D)?this.X="LIVE":this.videoData.captionTracks.length?this.X="INNERTUBE":this.videoData.mT&&(this.X="TTS");this.hN=this.B.controlsType==="3";this.iV=new L$(this.D,this.B);this.n8=new g.Re(this);this.C=new g.L({N:"div",Mi:"ytp-caption-window-container",K:{id:"ytp-caption-window-container"}});
this.f8={top:0,right:0,bottom:0,left:0,width:1,height:1};var a=null,N=g.gA("yt-html5-player-modules::subtitlesModuleData");N&&(a=new g.OA(N));this.storage=a;var k;this.K8=!((k=O.fD())==null||!k.wf());this.W=dcw(this);this.sU=!this.W&&this.hN&&this.K8&&(this.X==="LIVE"||this.X==="SABR_LIVE");g.n(this,this.iV);this.W?this.Py=this.ZG=null:(this.ZG=new g.Tk(this.f9,void 0,this),g.n(this,this.ZG),this.Py=new g.Hg(this.bO,2E3,this),g.n(this,this.Py));g.n(this,this.n8);g.P_(this.player,this.C.element,4);
g.n(this,this.C);this.W||this.n8.j(O,"resize",this.OL);(this.p8=g.PJ(this.B)&&!g.Ef()&&!this.D.isFullscreen()&&!this.W&&!this.sU)&&this.n8.j(O,"resize",this.GA);this.n8.j(O,"onPlaybackAudioChange",this.iz);this.n8.j(O,g.L8("captions"),function(D){b.onCueRangeEnter(D)});
this.n8.j(O,"crx_captions",function(D){b.onCueRangeExit(D)});
Xw(this,bO()||{});this.player.GG("onCaptionsModuleAvailable")},FFB=function(O){if(O.B.hL===1||O.videoData.xR===1||g.yz(O.videoData,"yt:cc")==="alwayson")return!0;
if(O.videoData.captionTracks.length)var b=O.getAudioTrack().G;if(O.B.hL===2){if(g.R9(O.B))var a=Zpw(O);else if(O.storage)try{a=O.storage.get("module-enabled")}catch(k){O.storage.remove("module-enabled")}else a=null;if(a!=null)return!!a}a=Q0(O.player.getAudioTrack(),g.R9(O.B));var N=g.yz(O.videoData,"yt:cc");if(QA(O)===void 0){if(a==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return N?N==="on":!0;if(a==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return N==="on"}else return N==="on";return b==="ON"||g.yz(O.videoData,
"yt:cc")==="on"},ec=function(O,b){if(O.T&&(b===void 0||!b)||!O.videoData.captionTracks.length)return!1;
O=O.getAudioTrack();return!!O.T||O.G==="FORCED_ON"},QA=function(O){var b=void 0,a=g.Bi(g.FZ(),65);
if(g.R9(O.B)&&a!=null){if(Zpw(O)!=null)return!1;b=!a}return b},ba=function(O,b){if(!O.G)return null;
if(O.S&&O.S.X)return O.S.X;b=go3(O,b);b=ah(O.G.G,b);var a=null;if(iSA(O.B)){var N=O.D.isInline()?void 0:g.by("yt-player-caption-sticky-language");for(var k=[N,O.videoData.captionsLanguagePreference,O.B.captionsLanguagePreference,g.yz(O.videoData,"yt:cc_default_lang")],D=!1,R=0;R<k.length;R++){var d=k[R];if(d){D=!0;for(var Z=0;Z<b.length;Z++)if(g.Ey(b[Z])===d)return b[Z];for(Z=0;Z<b.length;Z++)if(g.Ey(b[Z]).split("-")[0]===d.split("-")[0])return b[Z]}}if(D&&O.G&&(k=O.G.W,k.length))for(k=g.H(k),D=k.next();!D.done;D=
k.next())if(D=D.value,D.languageCode===N){a=D;break}}else for(N=[O.videoData.captionsLanguagePreference,O.B.captionsLanguagePreference,g.yz(O.videoData,"yt:cc_default_lang")],k=0;k<N.length;k++)for(D=0;D<b.length;D++)if(g.Ey(b[D])===N[k])return b[D];N=null;O.S&&O.S.V&&(N=O.S.V);N||(N=b.find(function(F){return F.isDefault})||null);
N||(N=b[0]||O2(O));N&&a&&g.Ey(N).split("-")[0]!==a.languageCode.split("-")[0]&&(N=Qde(N,a));return N},O2=function(O){return O.S&&O.S.T},aK=function(O){var b=O2(O);
return!!b&&O.T===b},BWQ=function(O,b){var a=O.D.fD().MJ().textTracks;
O=O.T.toString();for(var N=0;N<a.length;N++){var k=a[N];k.id===O&&(b?k.mode!=="showing"&&(k.mode="showing"):k.mode==="showing"&&(k.mode="disabled"))}},RK=function(O,b,a){O.loaded&&O.unload();
a!=null&&(O.Y=a,O.Y&&(g.R9(O.B)?Nv(O,!!b):kZ(O,!!b)));O.B.Z("html5_sends_cfs_after_caption_loaded")||O.B.Z("html5_sends_cfs_after_caption_parsed")?(b!==null||ec(O,!0)||D7(O,null,b,O.Y,!1),O.T=b,ec(O)&&(O.T=O2(O))):(D7(O,O.T,b,O.Y,!1),O.T=b,ec(O)&&(b=O2(O),D7(O,O.T,b,O.Y,!0),O.T=b));var N;s2(O,(N=O.T)!=null?N:void 0);O.load()},tLe=function(O,b){if(b instanceof HY){var a=O.wd[b.id];
a&&a.G!==b&&(a.dispose(),delete O.wd[b.id],a=null);a||(a=KFf(O,b))&&(O.wd[b.id]=a)}else a=b.windowId,O.UU[a]||(O.UU[a]=[]),O.UU[a].push(b)},KFf=function(O,b){var a=hQe(O);
if(!a)return null;var N=O.T?g.Ey(O.T):null;N&&g.lcf.test(N)&&(b.params.Db=1);var k=O.Fy.getPlayerSize();N=k.height*O.f8.height;k=k.width*O.f8.width;O.B.playerStyle!=="google-live"||O.V.isDefault||Object.assign(b.params,O.V);switch(b.params.kU!=null?b.params.kU:b.T.length>1?1:0){case 1:return new oh(b,O.V,O.U,a.width,a.height,k,N,O.B.experiments,O.W_.bind(O),O.D);case 2:return new Sc(b,O.V,O.U,a.width,a.height,k,N,O.B.experiments,O.W_.bind(O),O.D);default:return new ZA(b,O.V,O.U,a.width,a.height,k,
N,O.B.experiments,O.W_.bind(O),O.D)}},Xw=function(O,b,a){a=a===void 0?!1:a;
var N=$Z.Y1;O.V={};Object.assign(O.V,$Z);O.V.Y1={};Object.assign(O.V.Y1,N);O.U={Y1:{}};var k=b.backgroundOverride?O.U:O.V,D=b.background||N.background;EI.test(D);k.Y1.background=D;k=b.colorOverride?O.U:O.V;D=b.color||N.color;EI.test(D);k.Y1.color=D;k=b.windowColorOverride?O.U:O.V;D=b.windowColor||$Z.windowColor;EI.test(D);k.windowColor=D;k=b.backgroundOpacityOverride?O.U:O.V;D=b.backgroundOpacity;D==null&&(D=N.backgroundOpacity);k.Y1.backgroundOpacity=D;k=b.fontSizeIncrementOverride?O.U:O.V;D=b.fontSizeIncrement;
D==null&&(D=N.fontSizeIncrement);k.Y1.fontSizeIncrement=D;D=b.fontStyleOverride?O.U:O.V;k=b.fontStyle;k==null&&(k=N.bold&&N.italic?3:N.bold?1:N.italic?2:0);D=D.Y1;switch(k){case 1:D.bold=!0;delete D.italic;break;case 2:delete D.bold;D.italic=!0;break;case 3:D.bold=!0;D.italic=!0;break;default:delete D.bold,delete D.italic}k=b.textOpacityOverride?O.U:O.V;D=b.textOpacity;D==null&&(D=N.textOpacity);k.Y1.textOpacity=D;k=b.windowOpacityOverride?O.U:O.V;D=b.windowOpacity;D==null&&(D=$Z.windowOpacity);k.windowOpacity=
D;k=b.charEdgeStyleOverride?O.U:O.V;D=b.charEdgeStyle;D==null&&(D=N.charEdgeStyle);k.Y1.charEdgeStyle=D;k=b.fontFamilyOverride?O.U:O.V;D=b.fontFamily;D==null&&(D=N.fontFamily);k.Y1.fontFamily=D;O.loaded&&O.OL();a&&g.OO("yt-player-caption-display-settings",b,2592E3)},y$Q=function(O,b){if(!O.G)return{};
if(b){g.hc(b)||O.QW(b.vss_id,"m");if(O.W||!g.Cg(b))return;if(g.hc(b)){RK(O,null,!0);return}for(var a,N=ah(O.G.G,!0),k=0;k<N.length;k++){var D=N[k];D.languageCode!==b.languageCode||a&&(D.languageName!==b.languageName||(D.captionId||"")!==(b.captionId||"")||g.ns(D)!==b.displayName)||(a=b.translationLanguage?Qde(D,b.translationLanguage):D)}O.CR(b.position);!a||a===O.T&&O.loaded||(b=g.YX(),N=g.Ey(a),b.length&&N===b[b.length-1]||(b.push(N),g.OO("yt-player-caption-language-preferences",b)),iSA(O.B)&&!O.D.isInline()&&
g.OO("yt-player-caption-sticky-language",N,2592E3),RK(O,a,!0))}else return O.loaded&&O.T&&!aK(O)?eQ(O.T):{};return""},CZ=function(O,b,a){b&&!O.yl?(b=xNw({Db:0,
lang:"pt-BR"}),O.yl=[b,new WY(b.start,b.end-b.start,0,b.id,a!=null?a:"As legendas ficam assim")],O.player.z$(O.yl)):!b&&O.yl&&(wtz(O,O.yl),O.yl=null)},wtz=function(O,b){O.player.UX(b);
b=g.H(b);for(var a=b.next();!a.done;a=b.next())g.Cx(O.aX,a.value);io(O.ZG)},s2=function(O,b){O.B.Z("html5_modify_caption_vss_logging")&&(O.videoData.Ca=b)},hQe=function(O){var b=O.Fy.getVideoContentRect(!0).height,a=O.Fy.getVideoContentRect(!0).width;
if(!b||!a)return null;b*=O.f8.height;a*=O.f8.width;return{width:a,height:b}},kZ=function(O,b){if(O.storage)try{O.storage.set("module-enabled",b)}catch(a){}},Nv=function(O,b){O.D.isInline()||g.OO("yt-player-sticky-caption",b,2592E3)},Zpw=function(O){if(!O.D.isInline())return g.by("yt-player-sticky-caption")},dcw=function(O){var b,a=!((b=O.D.fD())==null||!b.fO());
return O.hN&&a&&O.X!=="LIVE"&&O.X!=="SABR_LIVE"},go3=function(O,b){g.cl(O.videoData)&&(b=!0);
b||(b=O.X==="TTS"?!1:O.X==="INNERTUBE"?!1:!0);return b||O.B.Z("web_deprecate_always_includes_asr_setting")&&g.R9(O.B)?!0:!!g.Bi(g.FZ(),66)},D7=function(O,b,a,N,k){O.B.Z("html5_sends_cfs_after_caption_loaded")||O.B.Z("html5_sends_cfs_after_caption_parsed")?O.u0(a,!!a,k?"g":N?"m":"s"):k?O.u0(a,!0,"g"):N?b?O.u0(a,!!a,"m"):a&&O.u0(a,!0,"m"):!b&&a&&O.u0(a,!0,"s")};
g.jX.prototype.TW=g.kb(43,function(){var O=g.Ys(document,"track",void 0,this.T);for(var b=0;b<O.length;b++)g.G8(O[b])});
g.SZ.prototype.TW=g.kb(42,function(){this.mediaElement.TW()});
g.jX.prototype.wf=g.kb(41,function(){return!(!this.T.textTracks||!this.T.textTracks.addEventListener)});
g.SZ.prototype.wf=g.kb(40,function(){return this.mediaElement.wf()});
g.jX.prototype.fO=g.kb(39,function(){return!!this.T.textTracks});
g.SZ.prototype.fO=g.kb(38,function(){return this.mediaElement.fO()});
g.jX.prototype.Iq=g.kb(37,function(O){for(var b=0;b<O.length;b++)this.T.appendChild(O[b])});
g.SZ.prototype.Iq=g.kb(36,function(O){this.mediaElement.Iq(O)});
g.og.prototype.ov=g.kb(35,function(O,b,a){this.r5.ov(O,b,a)});
g.dR.prototype.ov=g.kb(34,function(O,b,a){this.G.set(O,{aC:b,mD:a})});
g.Zh.prototype.ov=g.kb(33,function(O,b,a){this.f8.ov(O,b,a)});
g.og.prototype.Gn=g.kb(32,function(O){return this.r5.Gn(O)});
g.Zh.prototype.Gn=g.kb(31,function(O){var b=2;this.Y.has(O)?b=0:g.UR(this,O)&&(b=1);return b});
g.c_.prototype.CR=g.kb(26,function(O){var b;(b=g.dE(this.wP()))==null||b.CR(O)});
g.c_.prototype.U3=g.kb(25,function(O){var b=this.app.a8({playerType:void 0});return b?b.U3(O):!1});
g.lR.prototype.U3=g.kb(24,function(O){return this.L.P1.U3(O)});
g.KA.prototype.U3=g.kb(23,function(O){return this.H1().some(function(b){return b.namespace===O})});
g.eZ.prototype.U3=g.kb(22,function(){return!1});
g.c_.prototype.QW=g.kb(21,function(O,b){this.app.zr().QW(O,b)});
g.lR.prototype.QW=g.kb(20,function(O,b){this.L.QW(O,b)});
g.GB.prototype.QW=g.kb(19,function(O,b){O=[O,b];g.p4(this,g.GO(this.provider),"cfi",O)});
g.F$.prototype.QW=g.kb(18,function(O,b){this.qoe&&this.qoe.QW(O,b)});
g.X$.prototype.QW=g.kb(17,function(O,b){this.cB.QW(O,b)});
g.eZ.prototype.QW=g.kb(16,function(){});
g.c_.prototype.u0=g.kb(15,function(O,b,a){this.app.zr().u0(O,b,a)});
g.lR.prototype.u0=g.kb(14,function(O,b,a){this.L.u0(O,b,a)});
g.GB.prototype.u0=g.kb(13,function(O,b,a){if(this.aX!==O||this.vB!==b)b=b==="rawcc"?"":b,a=[O,b,this.aX,a],g.p4(this,g.GO(this.provider),"cfs",a),this.aX=O,this.vB=b});
g.F$.prototype.u0=g.kb(12,function(O,b,a){this.qoe&&this.qoe.u0(O,b,a)});
g.X$.prototype.u0=g.kb(11,function(O,b,a){this.cB.u0(O,b,a)});
g.eZ.prototype.u0=g.kb(10,function(){});
g.HG.prototype.Nj=g.kb(7,function(){return this.f8});
g.fq.prototype.Nj=g.kb(6,function(){return this.zr().u4()});
g.c_.prototype.u4=g.kb(5,function(){return this.app.Nj()});
g.lR.prototype.u4=g.kb(4,function(){return this.L.u4()});
g.X$.prototype.u4=g.kb(3,function(){var O;return((O=this.loader)==null?void 0:O.Nj())||null});
g.eZ.prototype.u4=g.kb(2,function(){return null});
g.aC.prototype.VF=g.kb(1,function(O){return(O=this.ZE(O))?O.T:0});
g.ES.prototype.VF=g.kb(0,function(){return 0});
var akf=/#(.)(.)(.)/,bVB=/^#(?:[0-9a-f]{3}){1,2}$/i,dN3={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};g.q(kP,g.m);g.T=kP.prototype;g.T.WP=function(){};
g.T.ZO=function(){};
g.T.HD=function(){};
g.T.ou=function(){return""};
g.T.xN=function(){return!1};
g.T.Kl=function(O,b){var a=this;if(this.uV.J().Z("html5_dispatch_tracklist_loaded_event")){this.X&&(this.X.reject(),this.X=null);var N=[];this.uV.publish("trackListLoaded",this.G,N,b);N.length?(b=new g.tq,b.promise.then(O.Kl,function(){}),this.X=b,Promise.all(N).then(b.resolve,b.reject).finally(function(){a.X=null})):O.Kl()}else O.Kl()};
g.T.kR=function(){};
g.T.Tr=function(){this.X&&(this.X.reject(),this.X=null);this.HD();g.m.prototype.Tr.call(this)};
g.q(DA,kP);DA.prototype.WP=function(O,b,a){var N=this;this.Xy();b=this.ou(O,b);var k=this.uV.J().Z("html5_report_captions_ctmp_qoe"),D=(0,g.S)();this.HD();sC3(this,b,{format:"RAW",onSuccess:function(R){N.T=null;if(k){var d=(R.responseText.length/1024).toFixed(),Z=(0,g.S)();N.videoData.lV("capresp",{ms:Z-D,kb:d})}a.aN(R.responseText,O)},
onError:k?function(R){var d;R=(d=R==null?void 0:R.status)!=null?d:0;N.videoData.lV("capfail",{status:R})}:void 0,
withCredentials:!0})};
DA.prototype.ZO=function(O){if(this.audioTrack)for(var b=g.H(this.audioTrack.captionTracks),a=b.next();!a.done;a=b.next())Nr(this.G,a.value);this.Kl(O,this.videoData.videoId)};
DA.prototype.ou=function(O,b){var a=O.qJ(),N={fmt:b};if(b==="srv3"||b==="3"||b==="json3")g.vb()?Object.assign(N,{xorb:2,xobt:1,xovt:1}):Object.assign(N,{xorb:2,xobt:3,xovt:3});O.translationLanguage&&(N.tlang=g.Ey(O));this.V&&(N.xosf="1");Object.assign(N,this.uV.J().T);return g.Qb(a,N)};
DA.prototype.HD=function(){this.T&&this.T.abort()};
sI.prototype.contains=function(O){O=g.ys(this.segments,O);return O>=0||O<0&&(-O-1)%2===1};
sI.prototype.length=function(){return this.segments.length/2};
g.q(Rh,g.m);g.T=Rh.prototype;g.T.Tr=function(){g.m.prototype.Tr.call(this);this.V&&this.V.cancel()};
g.T.M7=function(){this.seekTo(this.player.getCurrentTime())};
g.T.seekTo=function(O){O-=this.player.yp();var b=this.T;this.T=g.aR(this.yl.LM(O).EU);b!==this.T&&this.S&&this.S()};
g.T.reset=function(){this.X=new sI;this.Y=-1;this.V&&(this.V.cancel(),this.V=null)};
g.T.Un=function(){this.Xy();var O;if(O=this.T!=null)O=this.T,O=O.T.Z8(O);if(O&&!this.V&&!(this.T&&this.T.startTime-this.player.getCurrentTime()>30)){O=this.T;O=O.T.yD(O);var b=O.EU[0],a;if((a=this.player.getVideoData())==null?0:a.enableServerStitchedDai)if(a=this.player.u4()){var N=b.T.info.id,k=b.Gr,D=O.EU[0].X;if(this.policy.aX){if(a=a.WC(D,k,N,3))O.X=a}else if(N=a.oC(D,k,N,3))if(a=a.Gn(k),a===0)N&&(O.T=new g.SM(N));else if(a===2){this.U.start();$NQ(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.T.index.zD(b.Gr)?(this.X.contains(O.EU[0].Gr)||CH3(this,O),this.T=g.aR(O.EU)):$NQ(this)&&this.seekTo(this.player.getCurrentTime())}this.U.start()};
g.q($P,kP);g.T=$P.prototype;g.T.WP=function(O,b,a){var N=this;this.HD();b=FRB(this,O.getId());b||(b=O.languageCode,b=this.T.isManifestless?gwG(this,b,"386"):gwG(this,b));if(b){var k=(b.index.VF(b.index.gh())-b.index.getStartTime(b.index.gh()))*1E3,D=this.D.J(),R=new g.zs(D),d=function(){N.V&&N.V.reset();N.Y=!0};
D.Z("html5_keep_caption_data_after_seek")&&(d=null);this.V=new Rh(R,this.D,b,function(Z,F){a.aN(Z,O,F,k)},this.U||g.US(b.info),d)}};
g.T.xN=function(){var O=this.Y;this.Y=!1;return O};
g.T.ZO=function(O){var b=this.D.J().Z("html5_fallback_if_rawcc_missing");var a=this.T.T.rawcc!=null;if(!this.U||!a&&b)b=this.T.isManifestless?ZVA(this,"386"):ZVA(this);else{if(!a){this.logger.T(386248249,"rawcc used but unavailable");return}b=[new g.Jd({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Jd({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}b=g.H(b);
for(a=b.next();!a.done;a=b.next())Nr(this.G,a.value);O.Kl()};
g.T.HD=function(){this.V&&(this.V.dispose(),this.V=null)};
g.T.ou=function(){return""};
g.T.kR=function(){this.V&&(this.V.reset(),this.D.YA("captions"))};
g.q(C$,kP);C$.prototype.WP=function(O,b,a){var N=this;this.Xy();b=this.ou(O,b);this.HD();this.T=g.K6(b,{format:"RAW",onSuccess:function(k){N.T=null;a.aN(k.responseText,O)},
withCredentials:!0})};
C$.prototype.ZO=function(O){var b=this,a=this.V,N={type:"list",tlangs:1,v:this.videoId,vssids:1};this.K_&&(N.asrs=1);a=g.Qb(a,N);this.HD();this.T=g.K6(a,{format:"RAW",onSuccess:function(k){b.T=null;if((k=k.responseXML)&&k.firstChild){for(var D=k.getElementsByTagName("track"),R=0;R<D.length;R++){var d=D[R],Z=d.getAttribute("lang_code"),F=d.getAttribute("lang_translated"),B=d.getAttribute("name"),K=d.getAttribute("kind"),t=d.getAttribute("id"),h=d.getAttribute("lang_default")==="true",w=d.getAttribute("cantran")===
"true";d=d.getAttribute("vss_id");Nr(b.G,new g.Jd({languageCode:Z,languageName:F,name:B,kind:K,id:t,is_servable:!0,is_translateable:w,vss_id:d,is_default:h}))}k=k.getElementsByTagName("target");D=k.length;for(R=0;R<D;R++)Z={languageCode:k[R].getAttribute("lang_code"),languageName:k[R].getAttribute("lang_translated"),languageOriginal:k[R].getAttribute("lang_original"),id:k[R].getAttribute("id"),isDefault:k[R].getAttribute("lang_default")==="true"},b.Y[Z.languageCode]=Z.languageName,b.W.push(Z)}b.Kl(O,
b.videoId)},
withCredentials:!0})};
C$.prototype.ou=function(O,b){var a=this.V;b={v:this.videoId,type:"track",lang:O.languageCode,name:O.getName(),kind:O.kind,fmt:b};var N=this.uV.J();N.Z("captions_url_add_ei")&&(b.ei=this.eventId);O.translationLanguage&&(b.tlang=g.Ey(O));Object.assign(b,N.T);return a=g.Qb(a,b)};
C$.prototype.HD=function(){this.T&&this.T.abort()};
var EI=/^#(?:[0-9a-f]{3}){1,2}$/i;var txQ=["left","right","center","justify"];g.q(ZA,g.L);g.T=ZA.prototype;g.T.YP=function(O,b){this.hN=O;this.iV=b;var a=g.Lb(this.element,this.element.parentElement);this.By=O-a.x;this.Fy=b-a.y};
g.T.ut=function(O,b){if(O!==this.hN||b!==this.iV){g.Gk(this.element,"ytp-dragging")||g.oo(this.element,"ytp-dragging");var a=g.i9(this.element);O=O-this.By-.02*this.WB;var N=b-this.Fy-.02*this.Vp,k=(O+a.width/2)/this.maxWidth*3;k=Math.floor(g.Vw(k,0,2));var D=(N+a.height/2)/this.maxHeight*3;D=Math.floor(g.Vw(D,0,2));b=k+D*3;O=(O+k/2*a.width)/this.maxWidth;O=g.Vw(O,0,1)*100;a=(N+D/2*a.height)/this.maxHeight;a=g.Vw(a,0,1)*100;this.G.params.DW=b;this.G.params.Am=a;this.G.params.EF=O;this.G.params.isDefault=
!1;this.T.DW=b;this.T.Am=a;this.T.EF=O;this.T.isDefault=!1;this.f8.DW=b;this.f8.Am=a;this.f8.EF=O;this.f8.isDefault=!1;this.cR()}};
g.T.gp=function(){g.Pg(this.element,"ytp-dragging")};
g.T.cR=function(){this.gU(this.U)};
g.T.gU=function(O){var b=this.K8?0:Math.min(this.MX(),this.maxWidth),a=this.y0(),N=this.K8;if(N){var k=getComputedStyle(this.X.parentNode);k=Fw(k.borderLeftWidth)+Fw(k.borderRightWidth)+Fw(k.paddingLeft)+Fw(k.paddingRight)}else k=0;var D=k;k="";this.G.params.Db===3&&(k="rotate(180deg)");var R=N?"calc(96% - "+D+"px)":"96%";g.EE(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:a?a+"px":"","max-width":R,"max-height":R,margin:"",transform:""});this.B_(O);k={transform:k,top:"",left:"",
width:b?b+"px":"",height:a?a+"px":"","max-width":"","max-height":""};var d=this.T.EF*.96+2;R=this.T.DW;switch(R){case 0:case 3:case 6:(N=this.T.Y1.fontSizeIncrement)&&N>0&&this.T.Db!==2&&this.T.Db!==3&&(d=Math.max(d/(1+N*2),2));k.left=d+"%";break;case 1:case 4:case 7:k.left=d+"%";d=this.X.offsetWidth;b||d?(b=b||d+1,k.width=b+"px",k["margin-left"]=N?b/-2-D/2+"px":b/-2+"px"):k.transform+=" translateX(-50%)";break;case 2:case 5:case 8:k.right=100-d+"%"}N=this.T.Am*.96+2;switch(R){case 0:case 1:case 2:k.top=
N+"%";break;case 3:case 4:case 5:k.top=N+"%";(a=a||this.element.clientHeight)?(k.height=a+"px",k["margin-top"]=a/-2+"px"):k.transform+=" translateY(-50%)";break;case 6:case 7:case 8:k.bottom=100-N+"%"}g.EE(this.element,k);if(this.Y){a=this.X.offsetHeight;N=1;for(b=0;b<O.length;b++)k=O[b],typeof k.text==="string"&&(N+=k.text.split("\n").length-1,k.append||b===0||N++);a/=N;this.Y.style.height=a+"px";this.Y.style.width=a+"px";this.element.style.paddingLeft=a+5+"px";this.element.style.paddingRight=a+
5+"px";O=Number(this.element.style.marginLeft.replace("px",""))-a-5;a=Number(this.element.style.marginRight.replace("px",""))-a-5;this.element.style.marginLeft=O+"px";this.element.style.marginRight=a+"px"}};
g.T.B_=function(O){var b;for(b=0;b<O.length&&O[b]===this.U[b];b++);if(this.n8||this.U.length>b)b=0,this.n8=!1,this.U=[],this.C=this.ZG=this.aX=null,g.nm(this.X);for(;b<O.length;b++)rpw(this,O[b])};
g.T.MX=function(){return 0};
g.T.y0=function(){return 0};
g.T.toString=function(){return g.L.prototype.toString.call(this)};BY.prototype.clear=function(){this.V=this.time=this.mode=0;this.T=[];this.reset()};
BY.prototype.reset=function(){this.mode=0;this.X.reset(0);this.W.reset(1)};
var UN3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];K$.prototype.set=function(O){this.type=O};
K$.prototype.get=function(){return this.type};
t6.prototype.clear=function(){this.state=0};
t6.prototype.update=function(){this.state=this.state===2?1:0};
t6.prototype.NJ=function(){return this.state!==0};
t6.prototype.matches=function(O,b){return this.NJ()&&O===this.rT&&b===this.D8};
HVe.prototype.reset=function(){this.timestamp=this.T=0};
h6.prototype.updateTime=function(O){for(var b=1;b<=15;++b)for(var a=1;a<=32;++a)this.V[b][a].timestamp=O};
h6.prototype.debugString=function(){for(var O="\n",b=1;b<=15;++b){for(var a=1;a<=32;++a){var N=this.V[b][a];O=N.T===0?O+"_":O+String.fromCharCode(N.T)}O+="\n"}return O};
h6.prototype.reset=function(O){for(var b=0;b<=15;b++)for(var a=0;a<=32;a++)this.V[b][a].reset();this.X=O;this.T=0;this.G=this.row=1};
var Yd7=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],cpw=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],mNf=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],zoG=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];uO.prototype.reset=function(O,b){this.W=b;this.style.set(2);this.G=this.Y;this.X=this.U;this.T=this.G;var a=(O<<2)+(b<<1);this.Y.reset(a);this.U.reset(a);this.text.reset((O<<2)+(b<<1)+1)};
gV.prototype.reset=function(O){this.W=O;this.G.clear();this.X=this.V;this.V.reset(O,0);this.Y.reset(O,1)};pSe.prototype.X=function(){};g.q(WY,g.f8);WY.prototype.toString=function(){return g.f8.prototype.toString.call(this)};g.q(qr,g.m);qr.prototype.reset=function(){};g.q(HY,g.f8);HY.prototype.toString=function(){return g.f8.prototype.toString.call(this)};
var YP=0;g.q(cY,qr);cY.prototype.reset=function(){this.U={};this.G=this.T=null;this.Y=!0};
cY.prototype.V=function(O,b){O=O.firstChild;O.getAttribute("format");b=b||0;Number.isFinite(b);O=Array.from(O.childNodes);O=g.H(O);for(var a=O.next();!a.done;a=O.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "head":var N=a;break;case "body":var k=a}if(N)for(N=Array.from(N.childNodes),N=g.H(N),O=N.next();!O.done;O=N.next())if(O=O.value,O.nodeType===1)switch(O.tagName){case "pen":a=O.getAttribute("id");var D=this.pens,R={},d=O.getAttribute("p");d&&Object.assign(R,this.pens[d]);d=zt(O,"b");
d!=null&&(R.bold=d);d=zt(O,"i");d!=null&&(R.italic=d);d=zt(O,"u");d!=null&&(R.underline=d);d=J6(O,"et");d!=null&&(R.charEdgeStyle=d);d=J6(O,"of");d!=null&&(R.offset=d);d=Mr(O,"bc");d!=null&&(R.background=d);d=Mr(O,"ec");d!=null&&(R.H_=d);d=Mr(O,"fc");d!=null&&(R.color=d);d=J6(O,"fs");d!=null&&d!==0&&(R.fontFamily=d);d=m$(O,"sz");d!==void 0&&(R.fontSizeIncrement=d/100-1);d=m$(O,"bo");d!==void 0&&(R.backgroundOpacity=d/255);d=m$(O,"fo");d!==void 0&&(R.textOpacity=d/255);d=J6(O,"rb");d!=null&&d!==10&&
d!==0&&(R.Md=d>10?d-1:d);O=J6(O,"hg");O!=null&&(R.Ff=O);D[a]=R;break;case "ws":a=O.getAttribute("id");this.S[a]=PHQ(this,O);break;case "wp":a=O.getAttribute("id"),this.C[a]=vwz(this,O)}if(k){N=[];k=Array.from(k.childNodes);k=g.H(k);for(O=k.next();!O.done;O=k.next())if(O=O.value,O.nodeType===1)switch(O.tagName){case "w":this.T=jC3(this,O,b,!1);(O=this.U[this.T.id])&&O.end>this.T.start&&(O.end=this.T.start);this.U[this.T.id]=this.T;N.push(this.T);break;case "p":var Z=O;d=b;a=[];D=Z.getAttribute("w")||
this.W;R=!!zt(Z,"a");d=(m$(Z,"t")||0)+d;var F=m$(Z,"d")||5E3;R||(!this.Y&&this.G&&this.G.windowId===D&&this.G.end>d&&(this.G.end=d),this.G&&this.G.text==="\n"&&(this.G.text=""));var B=R?6:5,K=Z.getAttribute("p");K=K?this.pens[K]:null;var t=Array.from(Z.childNodes);t.length&&(this.Y=Z.getAttribute("d")!=null);for(Z=0;Z<t.length;Z++){var h=t[Z],w=void 0;Z>0&&(R=!0);var A=void 0;h.nodeType===1&&(A=h);if(A&&A.tagName==="s"){if((h=(h=A.getAttribute("p"))?this.pens[h]:null)&&h.Md&&(h.Md===1?(h=t.slice(Z,
Z+4),h.length===4&&(w=owQ(d,F,D,R,B,h,this.pens),Z+=3)):w=owQ(d,F,D,R,B,[A],this.pens)),!w){var W=A;w=d;A=F;h=D;var E=R,z=B,J=W.textContent?W.textContent:"",G=W.getAttribute("p");G=G?this.pens[G]:null;W=m$(W,"t")||0;w=new WY(w+W,A-W,z,h,J,E,G)}}else w=new WY(d,F,B,D,h.textContent||"",R,K);a.push(w);this.G=w}if(a.length>0)for(a[0].windowId===this.W&&(this.T=jC3(this,O,b,!0),N.push(this.T)),O=g.H(a),a=O.next();!a.done;a=O.next())a=a.value,a.windowId=this.T.id,this.T.T.push(a),N.push(a)}b=N}else b=[];
return b};var TWb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.q(n$,qr);n$.prototype.reset=function(){this.G.clear()};
n$.prototype.V=function(O,b){var a=JSON.parse(O);if(!a)return[];if(a.pens){O=0;for(var N=g.H(a.pens),k=N.next();!k.done;k=N.next()){k=k.value;var D={},R=k.pParentId;R&&Object.assign(D,this.T.get(R));k.bAttr&&(D.bold=!0);k.iAttr&&(D.italic=!0);k.uAttr&&(D.underline=!0);R=k.ofOffset;R!=null&&(D.offset=R);k.szPenSize!==void 0&&(D.fontSizeIncrement=k.szPenSize/100-1);R=k.etEdgeType;R!=null&&(D.charEdgeStyle=R);k.ecEdgeColor!==void 0&&(D.H_=p$(k.ecEdgeColor));R=k.fsFontStyle;R!=null&&R!==0&&(D.fontFamily=
R);k.fcForeColor!==void 0&&(D.color=p$(k.fcForeColor));k.foForeAlpha!==void 0&&(D.textOpacity=k.foForeAlpha/255);k.bcBackColor!==void 0&&(D.background=p$(k.bcBackColor));k.boBackAlpha!==void 0&&(D.backgroundOpacity=k.boBackAlpha/255);(R=k.rbRuby)&&R!==10&&(D.Md=R>10?R-1:R,D.textEmphasis=TWb.get(D.Md));k.hgHorizGroup&&(D.Ff=k.hgHorizGroup);this.T.set(O++,D)}}if(a.wsWinStyles)for(O=0,N=g.H(a.wsWinStyles),k=N.next();!k.done;k=N.next())k=k.value,D={},(R=k.wsParentId)?Object.assign(D,this.W.get(R)):Object.assign(D,
this.Y),k.mhModeHint!==void 0&&(D.kU=k.mhModeHint),k.juJustifCode!==void 0&&(D.textAlign=k.juJustifCode),k.pdPrintDir!==void 0&&(D.Db=k.pdPrintDir),k.sdScrollDir!==void 0&&(D.DF=k.sdScrollDir),k.wfcWinFillColor!==void 0&&(D.windowColor=p$(k.wfcWinFillColor)),k.wfoWinFillAlpha!==void 0&&(D.windowOpacity=k.wfoWinFillAlpha/255),this.W.set(O++,D);if(a.wpWinPositions)for(O=0,N=g.H(a.wpWinPositions),k=N.next();!k.done;k=N.next())k=k.value,D={},(R=k.wpParentId)&&Object.assign(D,this.X.get(R)),k.ahHorPos!==
void 0&&(D.EF=k.ahHorPos),k.apPoint!==void 0&&(D.DW=k.apPoint),k.avVerPos!==void 0&&(D.Am=k.avVerPos),k.ccCols!==void 0&&(D.UR=k.ccCols),k.rcRows!==void 0&&(D.HG=k.rcRows),this.X.set(O++,D);if(a.events){O=[];a=g.H(a.events);for(N=a.next();!N.done;N=a.next()){var d=N.value;k=(d.tStartMs||0)+b;D=d.dDurationMs||0;if(d.id)R=String(d.id),N=Sdf(this,d,k,D,R),O.push(N),this.G.set(R,N);else{d.wWinId?R=d.wWinId.toString():(R="_"+YP++,N=Sdf(this,d,k,D,R),O.push(N),this.G.set(R,N));N=O;var Z=d;D===0&&(D=5E3);
d=this.G.get(R);var F=!!Z.aAppend,B=F?6:5,K=Z.segs,t=null;Z.pPenId&&(t=this.T.get(Z.pPenId));for(Z=0;Z<K.length;Z++){var h=K[Z],w=h.utf8;if(w){var A=h.tOffsetMs||0,W=null;h.pPenId&&(W=this.T.get(h.pPenId));if((d.params.kU!=null?d.params.kU:d.T.length>1?1:0)===2&&F&&w==="\n")continue;h=null;var E=[],z;if(z=W&&W.Md===1){z=K;var J=Z;if(J+3>=z.length||!z[J+1].pPenId||!z[J+2].pPenId||!z[J+3].pPenId)z=!1;else{var G=z[J+1].pPenId;(G=this.T.get(G))&&G.Md&&G.Md===2?(G=z[J+2].pPenId,G=this.T.get(G),!G||!G.Md||
G.Md<3?z=!1:(G=z[J+3].pPenId,z=(G=this.T.get(G))&&G.Md&&G.Md===2?!0:!1)):z=!1}}if(z)A=K[Z+1].utf8,h=K[Z+3].utf8,z=K[Z+2].utf8,J=this.T.get(K[Z+2].pPenId),w=GTe(w,A,z,h,J),h=new WY(k,D,B,R,w,F,W),Z+=3;else{if(w.indexOf("<")>-1){var Cw=void 0;E=W;z=t;J=k;G=D;var NB=A,H8=B,$b=F,nw=[],ue=dV("<html>"+w+"</html>");if(!ue.getElementsByTagName("parsererror").length&&((Cw=ue.firstChild)==null?0:Cw.childNodes.length))for(Cw=g.H(ue.firstChild.childNodes),ue=Cw.next();!ue.done;ue=Cw.next()){ue=ue.value;var s$=
void 0,v8=void 0,oY=(v8=(s$=ue.textContent)==null?void 0:s$.replace(/\n/g,""))!=null?v8:"";if(ue.nodeType!==3||oY&&oY.match(/^ *$/)==null){s$={};Object.assign(s$,E||z);v8=void 0;switch((v8=ue)==null?void 0:v8.tagName){case "b":s$.bold=!0;break;case "i":s$.italic=!0;break;case "u":s$.underline=!0}nw.push(new WY(J+NB,G-NB,H8,d.id,oY,$b,s$))}}E=nw}E.length||(E=[new WY(k+A,D-A,B,d.id,w,F,W||t)])}if(E.length)for(F=g.H(E),W=F.next();!W.done;W=F.next())W=W.value,N.push(W),d.T.push(W);else h&&(N.push(h),
d.T.push(h))}F=!0}}}b=O}else b=[];return b};g.q(Gt,kP);Gt.prototype.WP=function(O,b,a){OVe(this.videoData.videoId,O.vssId,a.aN)};
Gt.prototype.ZO=function(O){if(this.audioTrack)for(var b=g.H(this.audioTrack.captionTracks),a=b.next();!a.done;a=b.next())Nr(this.G,a.value);O.Kl()};g.q(oh,ZA);oh.prototype.B_=function(O){var b=this.G.T;ZA.prototype.B_.call(this,O);for(O=O.length;O<b.length;O++){var a=b[O];if(D&&a.T===k)var N=D;else{N={};Object.assign(N,a.T);Object.assign(N,r$e);var k=a.T;var D=N}rpw(this,a,N)}};
var r$e={C6:!0};g.q(xP,pSe);xP.prototype.X=function(O,b,a,N,k){if(a<N){var D="_"+YP++;a=a/1E3-this.Y;N=N/1E3-this.Y;O=new HY(a,N-a,5,D,{textAlign:0,DW:0,EF:b*2.5,Am:O*5.33});k=new WY(a,N-a,5,D,k);this.G.push(O);this.G.push(k)}};
g.q(jc,qr);jc.prototype.V=function(O){O=new xP(O,O.byteLength,this.G);if(Ikb(O)){for(;O.byteOffset<O.T.byteLength;)for(O.version===0?O.V=vY(O)*(1E3/45):O.version===1&&(O.V=vY(O)*4294967296+vY(O)),O.W=PY(O);O.W>0;O.W--){var b=PY(O),a=PY(O),N=PY(O);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.T,b.T.push({time:O.V,type:this.track,sN:a,Tm:N,order:b.T.length}))}qdY(this.T,O);return O.G}return[]};
jc.prototype.reset=function(){this.T.clear()};g.q(Sc,ZA);g.T=Sc.prototype;g.T.cR=function(){g.cg(this.RX)};
g.T.OA=function(){this.element.removeEventListener("transitionend",this.OA,!1);g.Pg(this.element,"ytp-rollup-mode");this.gU(this.Ql,!0)};
g.T.y0=function(){return this.V?this.yl:this.S};
g.T.MX=function(){return this.V?this.S:this.yl};
g.T.gU=function(O,b){this.Ql=O;if(this.G.params.HG){for(var a=0,N=0;N<this.U.length&&a<O.length;N++)this.U[N]===O[a]&&a++;a>0&&a<O.length&&(O=this.U.concat(O.slice(a)));this.p8=this.yl;this.S=this.yl=0;ZA.prototype.gU.call(this,O);LRb(this,b)}ZA.prototype.gU.call(this,O)};Ih.prototype.unload=function(){this.T!=null&&(this.D.removeEventListener("sabrCaptionsDataLoaded",this.T),this.T=null);this.XX=[];this.D.publish("sabrCaptionsBufferedRangesUpdated",this.XX)};
Ih.prototype.W$=function(O){return{formatId:g.O8(O.info.T.info,this.G),Gr:O.info.Gr+(this.G?0:1),startTimeMs:O.info.X*1E3,durationMs:O.info.C*1E3}};g.q(f$,kP);g.T=f$.prototype;g.T.WP=function(O,b,a){this.HD();b=O.getId();b=b!=null&&b in this.T.T?this.T.T[b]:null;b||(b=O.languageCode,b=this.T.isManifestless?OpB(this,b,"386"):OpB(this,b));b&&(this.V=O,this.Y=b,QCB(this.U,a),this.D.publish("sabrCaptionsTrackChanged",g.O8(b.info,this.T.G)))};
g.T.ZO=function(O){var b=this.T.isManifestless?eop(this,"386"):eop(this);b=g.H(b);for(var a=b.next();!a.done;a=b.next())Nr(this.G,a.value);O.Kl()};
g.T.HD=function(){this.V&&(this.V=this.Y=null,this.U.unload(),this.D.publish("sabrCaptionsTrackChanged",null))};
g.T.ou=function(){return""};
g.T.kR=function(){this.D.YA("captions")};var aXY="WEBVTT".split("").map(function(O){return O.charCodeAt(0)});
g.q(lO,qr);
lO.prototype.V=function(O,b){O instanceof ArrayBuffer&&(O=g.iT(new Uint8Array(O)));var a=[];O=O.split(UcA);for(var N=1;N<O.length;N++){var k=O[N],D=b;if(k!==""&&!ubA.test(k)){var R=dr.exec(k);if(R&&R.length>=4){var d=VA(R[1]),Z=VA(R[2])-d;d+=D;var F=(R=R[3])?R.split(" "):[];R={};var B=null;var K="";var t=null,h="";F=g.H(F);for(var w=F.next();!w.done;w=F.next())if(w=w.value.split(":"),w.length===2){var A=w[1];switch(w[0]){case "line":w=A.split(",");w[0].endsWith("%")&&(B=w[0],R.Am=Number.parseInt(B,10),
w.length===2&&(K=w[1].trim()));break;case "position":w=A.split(",");t=w[0];R.EF=Number.parseInt(t,10);w.length===2&&(h=w[1].trim());break;case "align":switch(A){case "start":R.textAlign=0;break;case "middle":R.textAlign=2;break;case "end":R.textAlign=1}}}B||K||(K="end");if(!t)switch(R.textAlign){case 0:R.EF=0;break;case 1:R.EF=100;break;case 2:R.EF=50}if(R.textAlign!=null){B=0;switch(K){case "center":B+=3;break;case "end":B+=6;break;default:B+=0}switch(h){case "line-left":B+=0;break;case "center":B+=
1;break;case "line-right":B+=2;break;default:switch(R.textAlign){case 0:B+=0;break;case 2:B+=1;break;case 1:B+=2}}K=B<0||B>8?7:B;R.DW=K}k=k.substring(dr.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");h=R;R=k;k={};if(R.indexOf("<")<0&&R.indexOf("&")<0)D=Dcp(d,Z,5,h),Z=new WY(d,Z,5,D.id,R,!1,g.hc(k)?void 0:k),a.push(D),a.push(Z),D.T.push(Z);else for(K=R.split(A$B),K.length===1?(R=5,h=Dcp(d,Z,R,h)):(B=R=6,h=Object.assign({UR:32},h),h=new HY(d,Z,B,"_"+YP++,h)),a.push(h),B=d,t=0;t<K.length;t++)F=K[t],
t%2===0?(w=dV("<html>"+F+"</html>"),w.getElementsByTagName("parsererror").length?(A=w.createElement("span"),A.appendChild(w.createTextNode(F))):A=w.firstChild,kCe(this,B,Z-(B-d),R,h,t>0,A,k,a)):B=VA(F)+D}dr.lastIndex=0}}return a};
var ubA=/^NOTE/,UcA=/(?:\r\n|\r|\n){2,}/,dr=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),A$B=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.q(L$,g.m);L$.prototype.clear=function(){this.T&&this.T.dispose();this.T=null};
L$.prototype.reset=function(){this.T&&this.T.reset()};
L$.prototype.Tr=function(){g.m.prototype.Tr.call(this);this.clear()};var $Z={windowColor:"#080808",windowOpacity:0,textAlign:2,DW:7,EF:50,Am:100,isDefault:!0,Y1:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.q(iO,g.NW);g.T=iO.prototype;g.T.Tr=function(){if(this.W||this.sU){var O=this.D.fD();O&&!O.Xy()&&O.TW()}else CZ(this,!1);g.NW.prototype.Tr.call(this)};
g.T.X8=function(){return this.B.Z("html5_honor_caption_availabilities_in_audio_track")&&this.X!=="LIVE"&&this.X!=="SABR_LIVE"};
g.T.XC=function(){if(this.hN)return this.W||this.sU;var O=this.getAudioTrack();if(this.X8()){if(!O.captionTracks.length)return!1;if(!this.G)return!0}O=Q0(O,g.R9(this.B));return O==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:O==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?ec(this):QA(this)||ec(this)?!0:FFB(this)};
g.T.load=function(){g.NW.prototype.load.call(this);this.S=this.getAudioTrack();if(this.G)this.T&&(this.iV.clear(),this.W?BWQ(this,!0):this.player.getPresentingPlayerType()!==3&&this.G.WP(this.T,"json3",this.RX),this.W||this.sU||aK(this)||this.player.GG("captionschanged",eQ(this.T)));else{if(this.X==="OFFLINE")var O=new Gt(this.player,this.videoData,this.getAudioTrack());else this.X==="SABR_LIVE"?O=new f$(this.videoData.T,this.player):this.X==="LIVE"?O=new $P(this.videoData.T,this.player):this.X===
"INNERTUBE"?O=new DA(this.player,this.videoData,this.getAudioTrack()):(O=this.videoData,O=new C$(this.player,this.videoData.mT,this.videoData.videoId,O.captionsLanguagePreference||O.tN.captionsLanguagePreference||g.yz(O,"yt:cc_default_lang")||O.tN.Go,this.videoData.J6,this.videoData.eventId));this.G=O;g.n(this,this.G);this.G.ZO(this.RX)}};
g.T.unload=function(){this.W&&this.T?BWQ(this,!1):(this.Py&&g.mc(this.Py),this.player.YA("captions"),this.aX=[],this.G&&this.G.HD(),this.iV.clear(),this.yl&&this.player.z$(this.yl),this.OL());g.NW.prototype.unload.call(this);this.player.pR();this.player.GG("captionschanged",{})};
g.T.create=function(){this.XC()&&this.load();var O;a:{var b,a,N;if(this.B.Z("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(a=b.captions)==null?0:(N=a.playerCaptionsTracklistRenderer)==null?0:N.enableTouchCaptionsNitrate)){var k,D;if(b=(O=this.videoData.getPlayerResponse())==null?void 0:(k=O.captions)==null?void 0:(D=k.playerCaptionsTracklistRenderer)==null?void 0:D.captionTracks)for(O=g.H(b),k=O.next();!k.done;k=O.next())if(k=k.value,k.kind==="asr"&&k.languageCode===
"en"){O=!0;break a}}O=!1}O&&this.D.publish("showpromotooltip",this.C.element)};
g.T.Kl=function(){var O=Q0(this.player.getAudioTrack(),g.R9(this.B));var b=O==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?ba(this,this.Y):O==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&ec(this)?O2(this):QA(this)||this.Y||FFB(this)?ba(this,this.Y):ec(this)?O2(this):null;if(this.W||this.sU){var a=ah(this.G.G,!0);O=[];for(var N=0;N<a.length;N++){var k=a[N],D=g.Ms("TRACK");D.setAttribute("kind","subtitles");D.setAttribute("label",g.ns(k));D.setAttribute("srclang",g.Ey(k));D.setAttribute("id",k.toString());this.sU||
D.setAttribute("src",this.G.ou(k,"vtt"));k===b&&D.setAttribute("default","1");O.push(D)}b=this.D.fD();b.Iq(O);O=b.MJ();this.K8&&this.n8.j(O.textTracks,"change",this.jT)}else!this.T&&b&&RK(this,b),this.player.GG("onCaptionsTrackListChanged"),this.player.Xt("onApiChange")};
g.T.jT=function(){for(var O=this.D.fD().MJ().textTracks,b=null,a=0;a<O.length;a++)if(O[a].mode==="showing")a:{b=ah(this.G.G,!0);for(var N=0;N<b.length;N++)if(b[N].toString()===O[a].id){b=b[N];break a}b=null}(this.loaded?this.T:null)!==b&&RK(this,b,!0)};
g.T.fW=function(){!this.T&&this.W||this.unload()};
g.T.aN=function(O,b,a,N){if(O){var k;s2(this,(k=this.T)!=null?k:void 0);this.B.Z("html5_sends_cfs_after_caption_loaded")&&D7(this,null,this.T,this.Y,aK(this));this.G.xN()&&(this.aX=[],this.D.YA("captions"),io(this.ZG),this.iV.reset());a:{k=this.iV;N=N||0;a=RQG(k,O,a||0);O=[];try{for(var D=g.H(a),R=D.next();!R.done;R=D.next()){var d=R.value,Z=d.trackData,F=d.Pp,B=k.B.Z("safari_live_drm_captions_fix");if(typeof Z!=="string"){a=O;var K=a.concat;if(B&&NW3(Z))var t=$ce(k,Z,F);else{var h=k,w=b,A=Z,W=F,
E=N;if(!fk7(A))throw Error("Invalid binary caption track data");h.T||(h.T=new jc(E,w));t=h.T.V(A,W)}var z=K.call(a,t)}else{if(Z.substring(0,6)==="WEBVTT")var J=O.concat($ce(k,Z,F));else{a=O;var G=a.concat;b:{w=h=void 0;A=k;W=b;if(Z[0]==="{")try{A.T||(A.T=new n$(C5f(W)));var Cw=w=A.T.V(Z,F);break b}catch(v8){g.N_(v8);Cw=[];break b}var NB=dV(Z);if(!NB||!NB.firstChild){var H8=Error("Invalid caption track data");H8.params=Z;throw H8;}if(NB.firstChild.tagName==="timedtext"){if(Number(NB.firstChild.getAttribute("format"))===
3){A.T||(A.T=new cY(C5f(W),A.B));Cw=h=A.T.V(NB,F);break b}var $b=Error("Unsupported subtitles format in web player (Format2)");$b.params=Z;throw $b;}if(NB.firstChild.tagName==="transcript"){var nw=Error("Unsupported subtitles format in web player (Format1)");nw.params=Z;throw nw;}var ue=Error("Invalid caption track data");ue.params=Z;throw ue;}J=G.call(a,Cw)}z=J}O=z}var s$=O;break a}catch(v8){k.logger.T(187101178,"Captions parsing failed: "+v8.message+". ");k.clear();s$=[];break a}s$=void 0}b=s$;
this.B.Z("html5_sends_cfs_after_caption_parsed")&&!this.B.Z("html5_sends_cfs_after_caption_loaded")&&b.length>0&&D7(this,null,this.T,this.Y,aK(this));s$=!this.B.Z("html5_keep_caption_data_after_seek")&&(this.X==="LIVE"||this.X==="SABR_LIVE");this.player.z$(b,void 0,s$);!this.Y||this.sU||aK(this)||!this.B.Jq||g.XJ(this.B)||g.vJ(this.B)||g.jd(this.B)||this.B.yl==="shortspage"||this.player.isInline()||(g.mc(this.Py),b=xNw({DW:0,EF:5,Am:5,HG:2,textAlign:0,Db:0,lang:"pt-BR"}),this.Yk=[b],s$=["Clique em ",
" para configura\u00e7\u00f5es"],this.By||(D=new g.Q5(g.n8()),g.n(this,D),this.By=D.element),D=b.end-b.start,(R=g.ns(this.T))&&this.Yk.push(new WY(b.start,D,0,b.id,R)),this.Yk.push(new WY(b.start,D,0,b.id,s$[0]),new WY(b.start,D,0,b.id,this.By,!0),new WY(b.start,D,0,b.id,s$[1],!0)),this.player.z$(this.Yk),g.Y$(this.Py));!this.Y||this.sU||aK(this)||(g.R9(this.B)?Nv(this,!0):kZ(this,!0),this.S&&(this.S.X=this.T),this.player.pR());this.Y=!1}};
g.T.onCueRangeEnter=function(O){this.aX.push(O);io(this.ZG)};
g.T.onCueRangeExit=function(O){g.Cx(this.aX,O);this.G instanceof $P&&this.G.U&&this.player.UX([O]);io(this.ZG)};
g.T.getCaptionWindowContainerId=function(){return this.C.element.id};
g.T.bO=function(){wtz(this,this.Yk);this.Yk=null};
g.T.f9=function(){var O=this;if(!this.p8||!this.W){this.ZG.stop();g.yV(this.UU);this.aX.sort(g.V_);var b=this.aX;if(this.yl){var a=g.pF(b,function(D){return this.yl.indexOf(D)===-1},this);
a.length&&(b=a)}b=g.H(b);for(a=b.next();!a.done;a=b.next())tLe(this,a.value);b=g.H(Object.entries(this.wd));var N=b.next();for(a={};!N.done;a={j9:void 0,n$:void 0},N=b.next()){var k=g.H(N.value);N=k.next().value;k=k.next().value;a.j9=N;a.n$=k;this.UU[a.j9]?(a.n$.element.parentNode||(a.n$ instanceof Sc||a.n$ instanceof oh||g.RW(this.wd,function(D){return function(R,d){d!==D.j9&&R.G.params.DW===D.n$.G.params.DW&&R.G.params.EF===D.n$.G.params.EF&&R.G.params.Am===D.n$.G.params.Am&&(R.dispose(),delete O.wd[d]);
return d===D.j9}}(a),this),this.C.element.appendChild(a.n$.element)),a.n$.gU(this.UU[a.j9])):(a.n$.dispose(),delete this.wd[a.j9])}}};
g.T.Jv=function(){Xw(this,{},!0);this.player.GG("captionssettingschanged")};
g.T.w6=function(){var O=$Z.Y1;O={background:O.background,backgroundOpacity:O.backgroundOpacity,charEdgeStyle:O.charEdgeStyle,color:O.color,fontFamily:O.fontFamily,fontSizeIncrement:O.fontSizeIncrement,fontStyle:O.bold&&O.italic?3:O.bold?1:O.italic?2:0,textOpacity:O.textOpacity,windowColor:$Z.windowColor,windowOpacity:$Z.windowOpacity};var b=bO()||{};b.background!=null&&(O.background=b.background);b.backgroundOverride!=null&&(O.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(O.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(O.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(O.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(O.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(O.color=b.color);b.colorOverride!=null&&(O.colorOverride=b.colorOverride);b.fontFamily!=null&&(O.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(O.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(O.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(O.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(O.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(O.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(O.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(O.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(O.windowColor=b.windowColor);b.windowColorOverride!=null&&(O.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(O.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(O.windowOpacityOverride=b.windowOpacityOverride);return O};
g.T.Tz=function(O,b){var a={};Object.assign(a,bO());Object.assign(a,O);Xw(this,a,b);this.player.GG("captionssettingschanged")};
g.T.OL=function(){!this.W&&this.loaded&&(g.ks(this.wd,function(O,b){O.dispose();delete this.wd[b]},this),this.f9())};
g.T.n0=function(O,b){switch(O){case "fontSize":if(isNaN(b))break;O=g.Vw(b,-2,4);this.Tz({fontSizeIncrement:O});return O;case "reload":b&&!this.W&&RK(this,this.T,!0);break;case "stickyLoading":b!==void 0&&this.B.S&&(g.R9(this.B)?Nv(this,!!b):kZ(this,!!b));break;case "track":return y$Q(this,b);case "tracklist":return this.G?g.rx(ah(this.G.G,!(!b||!b.includeAsr)),function(a){return eQ(a)}):[];
case "translationLanguages":return this.G?this.G.W.map(function(a){return Object.assign({},a)}):[];
case "sampleSubtitles":this.W||b===void 0||CZ(this,!!b);break;case "sampleSubtitlesCustomized":this.W||CZ(this,!!b,b);break;case "recommendedTranslationLanguages":return g.YX();case "defaultTranslationSourceTrackIndices":return this.G?this.G.C:[]}};
g.T.getOptions=function(){var O="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.B.S&&O.push("stickyLoading");return O};
g.T.uH=function(){var O=this.T;if(this.D.U3("captions")){if(this.B.Z("html5_modify_caption_vss_logging")){var b;return(O=(b=this.videoData.Ca)!=null?b:null)?{cc:g.M2(O)}:{}}if(O)return b=O.vssId,O.translationLanguage&&b&&(b="t"+b+"."+g.Ey(O)),{cc:b}}return{}};
g.T.JA=function(){this.isSubtitlesOn()?(g.R9(this.B)?Nv(this,!1):kZ(this,!1),s2(this),RK(this,null,!0)):this.m7()};
g.T.m7=function(){var O=aK(this)||!this.T?ba(this,!0):this.T;O&&this.QW(O.vssId,"m");this.isSubtitlesOn()||RK(this,aK(this)||!this.T?ba(this,!0):this.T,!0)};
g.T.isSubtitlesOn=function(){return!!this.loaded&&!!this.T&&!aK(this)};
g.T.iz=function(){var O=aK(this);ec(this,O)?RK(this,this.getAudioTrack().T,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.X8()&&(this.Y=!1,this.T=null,this.G&&(this.G.dispose(),this.G=null)),this.XC()&&(O?RK(this,ba(this,!1),!1):this.load()))};
g.T.CR=function(O){O&&(this.f8={top:O.top,right:O.right,bottom:O.bottom,left:O.left,width:1-O.left-O.right,height:1-O.top-O.bottom},this.C.element.style.top=this.f8.top*100+"%",this.C.element.style.left=this.f8.left*100+"%",this.C.element.style.width=this.f8.width*100+"%",this.C.element.style.height=this.f8.height*100+"%",this.C.element.style.position="absolute",O=hQe(this))&&(this.C.element.style.width=O.width+"px",this.C.element.style.height=O.height+"px")};
g.T.onVideoDataChange=function(O,b){O==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.Y=!1,this.T=null,this.G&&(this.G.dispose(),this.G=null,this.player.GG("captionschanged",{})),this.XC()&&this.load())};
g.T.getAudioTrack=function(){return this.player.getAudioTrack()};
g.T.GA=function(){var O=this.D.fD();O&&!O.Xy()&&O.TW();this.D.isFullscreen()?(this.W=this.hN=!0,this.loaded&&this.Kl()):(this.hN=this.B.controlsType==="3",this.W=dcw(this));RK(this,this.T)};
g.T.W_=function(){var O,b,a,N=(O=this.videoData.getPlayerResponse())==null?void 0:(b=O.captions)==null?void 0:(a=b.playerCaptionsTracklistRenderer)==null?void 0:a.openTranscriptCommand;N&&this.player.CF("innertubeCommand",N)};
g.T.u0=function(O,b,a){var N=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,k="";O&&(k=O.vssId,k=k.replace(N,""));var D="";O&&O.getId()&&(D=O.getId()||"");O&&O.getXtags()&&(O=O.getXtags(),O=O.replace(N,""),D=D.concat(";"+O));this.D.u0(b?k:"",b?D:"",a)};
g.T.QW=function(O,b){O=(O||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");O.length>0&&this.D.QW(O,b)};
g.T.kR=function(){this.G&&this.G.kR()};g.a7("captions",iO);})(_yt_player);
